---
name: terraform

on:
  push:
    branches:
      - master
    paths-ignore:
      - config1/**
      - config2/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - config1/**
      - config2/**

jobs:
  config1:
    runs-on: ubuntu-20.04
    steps:
      - name: Print info
        run: echo "No Terraform actions required"
  config2:
    runs-on: ubuntu-20.04
    steps:
      - name: Print info
        run: echo "No Terraform actions required"
